inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

# Some long comments in the JSON Schema cause this to be un-enforceable
Layout/LineLength:
  Max: 1000

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
