name: cucumber_messages
description: JSON schema-based messages for Cucumber inter-process communication.
version: 0.0.1
homepage: https://github.com/cucumber/messages
repository: https://github.com/cucumber/messages
issue_tracker: https://github.com/cucumber/messages/issues
documentation: https://github.com/cucumber/messages/tree/main/dart

environment:
  sdk: ^3.9.0

topics:
  - cucumber
  - testing
  - json
  - ndjson

dependencies:

dev_dependencies:
  test: ^1.26.0
  very_good_analysis: ^10.0.0
