<?php

declare(strict_types=1);

/**
 * This code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
 */

namespace Cucumber\Messages\Hook;

enum Type: string
{
    case BEFORE = 'BEFORE';
    case AFTER = 'AFTER';
    case BEFORE_STEP = 'BEFORE_STEP';
    case AFTER_STEP = 'AFTER_STEP';
}
