# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    class AttachmentContentEncoding
      IDENTITY = 'IDENTITY'
      BASE64 = 'BASE64'
    end
  end
end
