require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the Comment message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # *
    #  A comment in a Gherkin document
    ##
    class Comment < ::Cucumber::Messages::Message
      ##
      # The location of the comment
      ##
      attr_reader :location

      ##
      # The text of the comment
      ##
      attr_reader :text

      def initialize(
        location: Location.new,
        text: ''
      )
        @location = location
        @text = text
        super()
      end
    end
  end
end
