require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the Exception message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # A simplified representation of an exception
    ##
    class Exception < ::Cucumber::Messages::Message
      ##
      # The type of the exception that caused this result. E.g. "Error" or "org.opentest4j.AssertionFailedError"
      ##
      attr_reader :type

      ##
      # The message of exception that caused this result. E.g. expected: "a" but was: "b"
      ##
      attr_reader :message

      ##
      # The stringified stack trace of the exception that caused this result
      ##
      attr_reader :stack_trace

      def initialize(
        type: '',
        message: nil,
        stack_trace: nil
      )
        @type = type
        @message = message
        @stack_trace = stack_trace
        super()
      end
    end
  end
end
