require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the Git message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # Information about Git, provided by the Build/CI server as environment
    #  variables.
    ##
    class Git < ::Cucumber::Messages::Message
      attr_reader :remote

      attr_reader :revision

      attr_reader :branch

      attr_reader :tag

      def initialize(
        remote: '',
        revision: '',
        branch: nil,
        tag: nil
      )
        @remote = remote
        @revision = revision
        @branch = branch
        @tag = tag
        super()
      end
    end
  end
end
