# frozen_string_literal: true

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/codegen/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the GlobalHookFinished message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    ##
    class GlobalHookFinished < Message
      ##
      # Identifier for the hook execution that has finished
      ##
      attr_reader :global_hook_started_id

      attr_reader :result

      attr_reader :timestamp

      def initialize(
        global_hook_started_id: '',
        result: TestStepResult.new,
        timestamp: Timestamp.new
      )
        @global_hook_started_id = global_hook_started_id
        @result = result
        @timestamp = timestamp
        super()
      end

      ##
      # Returns a new GlobalHookFinished from the given hash.
      # If the hash keys are camelCased, they are properly assigned to the
      # corresponding snake_cased attributes.
      #
      #   Cucumber::Messages::GlobalHookFinished.from_h(some_hash) # => #<Cucumber::Messages::GlobalHookFinished:0x... ...>
      ##
      def self.from_h(hash)
        return nil if hash.nil?

        new(
          global_hook_started_id: hash[:globalHookStartedId],
          result: TestStepResult.from_h(hash[:result]),
          timestamp: Timestamp.from_h(hash[:timestamp])
        )
      end
    end
  end
end
