require 'cucumber/messages/message'

"New name - group.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the Group message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class Group < ::Cucumber::Messages::Message
      attr_reader :children

      attr_reader :start

      attr_reader :value

      def initialize(
        children: [],
        start: nil,
        value: nil
      )
        @children = children
        @start = start
        @value = value
        super()
      end
    end
  end
end
