require 'cucumber/messages/message'

"New name - java_stack_trace_element.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the JavaStackTraceElement message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class JavaStackTraceElement < ::Cucumber::Messages::Message
      attr_reader :class_name

      attr_reader :file_name

      attr_reader :method_name

      def initialize(
        class_name: '',
        file_name: '',
        method_name: ''
      )
        @class_name = class_name
        @file_name = file_name
        @method_name = method_name
        super()
      end
    end
  end
end
