require 'cucumber/messages/message'

"New name - java_method.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the JavaMethod message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class JavaMethod < ::Cucumber::Messages::Message
      attr_reader :class_name

      attr_reader :method_name

      attr_reader :method_parameter_types

      def initialize(
        class_name: '',
        method_name: '',
        method_parameter_types: []
      )
        @class_name = class_name
        @method_name = method_name
        @method_parameter_types = method_parameter_types
        super()
      end
    end
  end
end
