require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the Location message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # *
    #  Points to a line and a column in a text file
    ##
    class Location < ::Cucumber::Messages::Message
      attr_reader :line

      attr_reader :column

      def initialize(
        line: 0,
        column: nil
      )
        @line = line
        @column = column
        super()
      end
    end
  end
end
