require 'cucumber/messages/message'

"New name - pickle_step.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the PickleStep message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # *
    #  An executable step
    ##
    class PickleStep < ::Cucumber::Messages::Message
      attr_reader :argument

      ##
      # References the IDs of the source of the step. For Gherkin, this can be
      #  the ID of a Step, and possibly also the ID of a TableRow
      ##
      attr_reader :ast_node_ids

      ##
      # A unique ID for the PickleStep
      ##
      attr_reader :id

      ##
      # The context in which the step was specified: context (Given), action (When) or outcome (Then).
      #
      # Note that the keywords `But` and `And` inherit their meaning from prior steps and the `*` 'keyword' doesn't have specific meaning (hence Unknown)
      ##
      attr_reader :type

      attr_reader :text

      def initialize(
        argument: nil,
        ast_node_ids: [],
        id: '',
        type: nil,
        text: ''
      )
        @argument = argument
        @ast_node_ids = ast_node_ids
        @id = id
        @type = type
        @text = text
        super()
      end
    end
  end
end
