require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the PickleTag message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # *
    #  A tag
    ##
    class PickleTag < ::Cucumber::Messages::Message
      attr_reader :name

      ##
      # Points to the AST node this was created from
      ##
      attr_reader :ast_node_id

      def initialize(
        name: '',
        ast_node_id: ''
      )
        @name = name
        @ast_node_id = ast_node_id
        super()
      end
    end
  end
end
