require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the PickleTable message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class PickleTable < ::Cucumber::Messages::Message
      attr_reader :rows

      def initialize(
        rows: []
      )
        @rows = rows
        super()
      end
    end
  end
end
