require 'cucumber/messages/message'

"New name - pickle_table_row.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the PickleTableRow message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class PickleTableRow < ::Cucumber::Messages::Message
      attr_reader :cells

      def initialize(
        cells: []
      )
        @cells = cells
        super()
      end
    end
  end
end
