require 'cucumber/messages/message'

"New name - pickle_step_argument.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the PickleStepArgument message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # An optional argument
    ##
    class PickleStepArgument < ::Cucumber::Messages::Message
      attr_reader :doc_string

      attr_reader :data_table

      def initialize(
        doc_string: nil,
        data_table: nil
      )
        @doc_string = doc_string
        @data_table = data_table
        super()
      end
    end
  end
end
