require 'cucumber/messages/message'

"New name - pickle_doc_string.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the PickleDocString message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class PickleDocString < ::Cucumber::Messages::Message
      attr_reader :media_type

      attr_reader :content

      def initialize(
        media_type: nil,
        content: ''
      )
        @media_type = media_type
        @content = content
        super()
      end
    end
  end
end
