require 'cucumber/messages/message'

"New name - pickle_table_cell.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the PickleTableCell message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class PickleTableCell < ::Cucumber::Messages::Message
      attr_reader :value

      def initialize(
        value: ''
      )
        @value = value
        super()
      end
    end
  end
end
