require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the Product message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # Used to describe various properties of Meta
    ##
    class Product < ::Cucumber::Messages::Message
      ##
      # The product name
      ##
      attr_reader :name

      ##
      # The product version
      ##
      attr_reader :version

      def initialize(
        name: '',
        version: nil
      )
        @name = name
        @version = version
        super()
      end
    end
  end
end
