require 'cucumber/messages/message'

"New name - rule.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the Rule message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class Rule < ::Cucumber::Messages::Message
      ##
      # The location of the `Rule` keyword
      ##
      attr_reader :location

      ##
      # All the tags placed above the `Rule` keyword
      ##
      attr_reader :tags

      attr_reader :keyword

      attr_reader :name

      attr_reader :description

      attr_reader :children

      attr_reader :id

      def initialize(
        location: Location.new,
        tags: [],
        keyword: '',
        name: '',
        description: '',
        children: [],
        id: ''
      )
        @location = location
        @tags = tags
        @keyword = keyword
        @name = name
        @description = description
        @children = children
        @id = id
        super()
      end
    end
  end
end
