require 'cucumber/messages/message'

"New name - step_match_arguments_list.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the StepMatchArgumentsList message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class StepMatchArgumentsList < ::Cucumber::Messages::Message
      attr_reader :step_match_arguments

      def initialize(
        step_match_arguments: []
      )
        @step_match_arguments = step_match_arguments
        super()
      end
    end
  end
end
