require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the StepDefinition message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class StepDefinition < ::Cucumber::Messages::Message
      attr_reader :id

      attr_reader :pattern

      attr_reader :source_reference

      def initialize(
        id: '',
        pattern: StepDefinitionPattern.new,
        source_reference: SourceReference.new
      )
        @id = id
        @pattern = pattern
        @source_reference = source_reference
        super()
      end
    end
  end
end
