require 'cucumber/messages/message'

"New name - table_cell.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the TableCell message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # A cell in a `TableRow`
    ##
    class TableCell < ::Cucumber::Messages::Message
      ##
      # The location of the cell
      ##
      attr_reader :location

      ##
      # The value of the cell
      ##
      attr_reader :value

      def initialize(
        location: Location.new,
        value: ''
      )
        @location = location
        @value = value
        super()
      end
    end
  end
end
