require 'cucumber/messages/message'

"New name - table_row.rb"
# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the TableRow message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    #
    # A row in a table
    ##
    class TableRow < ::Cucumber::Messages::Message
      ##
      # The location of the first cell in the row
      ##
      attr_reader :location

      ##
      # Cells in the row
      ##
      attr_reader :cells

      attr_reader :id

      def initialize(
        location: Location.new,
        cells: [],
        id: ''
      )
        @location = location
        @cells = cells
        @id = id
        super()
      end
    end
  end
end
