require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the TestRunStarted message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class TestRunStarted < Message
      attr_reader :timestamp

      def initialize(
        timestamp: Timestamp.new
      )
        @timestamp = timestamp
        super()
      end

      ##
      # Returns a new TestRunStarted from the given hash.
      # If the hash keys are camelCased, they are properly assigned to the
      # corresponding snake_cased attributes.
      #
      #   Cucumber::Messages::TestRunStarted.from_h(some_hash) # => #<Cucumber::Messages::TestRunStarted:0x... ...>
      ##
      def self.from_h(hash)
        return nil if hash.nil?

        new(
          timestamp: Timestamp.from_h(hash[:timestamp]),
        )
      end
    end
  end
end
