require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the TestRunStarted message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class TestRunStarted < ::Cucumber::Messages::Message
      attr_reader :timestamp

      def initialize(
        timestamp: Timestamp.new
      )
        @timestamp = timestamp
        super()
      end
    end
  end
end
