require 'cucumber/messages/message'

# The code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/jsonschema/scripts/codegen.rb]
module Cucumber
  module Messages
    ##
    # Represents the TestRunFinished message in Cucumber's {message protocol}[https://github.com/cucumber/messages].
    ##
    class TestRunFinished < ::Cucumber::Messages::Message
      ##
      # An informative message about the test run. Typically additional information about failure, but not necessarily.
      ##
      attr_reader :message

      ##
      # A test run is successful if all steps are either passed or skipped, all before/after hooks passed and no other exceptions where thrown.
      ##
      attr_reader :success

      ##
      # Timestamp when the TestRun is finished
      ##
      attr_reader :timestamp

      ##
      # Any exception thrown during the test run, if any. Does not include exceptions thrown while executing steps.
      ##
      attr_reader :exception

      def initialize(
        message: nil,
        success: false,
        timestamp: Timestamp.new,
        exception: nil
      )
        @message = message
        @success = success
        @timestamp = timestamp
        @exception = exception
        super()
      end
    end
  end
end
