# generated by datamodel-codegen:
#   filename:  Envelope.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from .json_converter import JSONDataclassMixin


class ContentEncoding(Enum):
    identity = "IDENTITY"
    base64 = "BASE64"


class MediaType(Enum):
    text_x_cucumber_gherkin_plain = "text/x.cucumber.gherkin+plain"
    text_x_cucumber_gherkin_markdown = "text/x.cucumber.gherkin+markdown"


@dataclass
class Source(JSONDataclassMixin):
    uri: str
    """
    *
     The [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)
     of the source, typically a file path relative to the root directory
    """
    data: str
    """
    The contents of the file
    """
    media_type: MediaType
    """
    The media type of the file. Can be used to specify custom types, such as
     text/x.cucumber.gherkin+plain
    """


@dataclass
class Location(JSONDataclassMixin):
    line: int
    column: int | None = None


@dataclass
class Comment(JSONDataclassMixin):
    location: Location
    """
    The location of the comment
    """
    text: str
    """
    The text of the comment
    """


@dataclass
class DocString(JSONDataclassMixin):
    location: Location
    content: str
    delimiter: str
    media_type: str | None = None


class KeywordType(Enum):
    unknown = "Unknown"
    context = "Context"
    action = "Action"
    outcome = "Outcome"
    conjunction = "Conjunction"


@dataclass
class TableCell(JSONDataclassMixin):
    location: Location
    """
    The location of the cell
    """
    value: str
    """
    The value of the cell
    """


@dataclass
class TableRow(JSONDataclassMixin):
    location: Location
    """
    The location of the first cell in the row
    """
    cells: list[TableCell]
    """
    Cells in the row
    """
    id: str


@dataclass
class Tag(JSONDataclassMixin):
    location: Location
    """
    Location of the tag
    """
    name: str
    """
    The name of the tag (including the leading `@`)
    """
    id: str
    """
    Unique ID to be able to reference the Tag from PickleTag
    """


class Type(Enum):
    before_test_run = "BEFORE_TEST_RUN"
    after_test_run = "AFTER_TEST_RUN"
    before_test_case = "BEFORE_TEST_CASE"
    after_test_case = "AFTER_TEST_CASE"
    before_test_step = "BEFORE_TEST_STEP"
    after_test_step = "AFTER_TEST_STEP"


@dataclass
class JavaMethod(JSONDataclassMixin):
    class_name: str
    method_name: str
    method_parameter_types: list[str]


@dataclass
class JavaStackTraceElement(JSONDataclassMixin):
    class_name: str
    file_name: str
    method_name: str


@dataclass
class Git(JSONDataclassMixin):
    remote: str
    revision: str
    branch: str | None = None
    tag: str | None = None


@dataclass
class Product(JSONDataclassMixin):
    name: str
    """
    The product name
    """
    version: str | None = None
    """
    The product version
    """


@dataclass
class PickleDocString(JSONDataclassMixin):
    content: str
    media_type: str | None = None


class Type1(Enum):
    unknown = "Unknown"
    context = "Context"
    action = "Action"
    outcome = "Outcome"


@dataclass
class PickleTableCell(JSONDataclassMixin):
    value: str


@dataclass
class PickleTableRow(JSONDataclassMixin):
    cells: list[PickleTableCell]


@dataclass
class PickleTag(JSONDataclassMixin):
    name: str
    ast_node_id: str
    """
    Points to the AST node this was created from
    """


class Type2(Enum):
    cucumber_expression = "CUCUMBER_EXPRESSION"
    regular_expression = "REGULAR_EXPRESSION"


@dataclass
class StepDefinitionPattern(JSONDataclassMixin):
    source: str
    type: Type2


@dataclass
class Group(JSONDataclassMixin):
    children: list[Group]
    start: int | None = None
    value: str | None = None


@dataclass
class StepMatchArgument(JSONDataclassMixin):
    group: Group
    """
    *
     Represents the outermost capture group of an argument. This message closely matches the
     `Group` class in the `cucumber-expressions` library.
    """
    parameter_type_name: str | None = None


@dataclass
class StepMatchArgumentsList(JSONDataclassMixin):
    step_match_arguments: list[StepMatchArgument]


@dataclass
class TestStep(JSONDataclassMixin):
    id: str
    hook_id: str | None = None
    """
    Pointer to the `Hook` (if derived from a Hook)
    """
    pickle_step_id: str | None = None
    """
    Pointer to the `PickleStep` (if derived from a `PickleStep`)
    """
    step_definition_ids: list[str] | None = None
    """
    Pointer to all the matching `StepDefinition`s (if derived from a `PickleStep`)
     Each element represents a matching step definition. A size of 0 means `UNDEFINED`,
     and a size of 2+ means `AMBIGUOUS`
    """
    step_match_arguments_lists: list[StepMatchArgumentsList] | None = None
    """
    A list of list of StepMatchArgument (if derived from a `PickleStep`).
    """


@dataclass
class Timestamp(JSONDataclassMixin):
    seconds: int
    """
    Represents seconds of UTC time since Unix epoch
     1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
     9999-12-31T23:59:59Z inclusive.
    """
    nanos: int
    """
    Non-negative fractions of a second at nanosecond resolution. Negative
     second values with fractions must still have non-negative nanos values
     that count forward in time. Must be from 0 to 999,999,999
     inclusive.
    """


@dataclass
class TestCaseStarted(JSONDataclassMixin):
    attempt: int
    """
    *
     The first attempt should have value 0, and for each retry the value
     should increase by 1.
    """
    id: str
    """
    *
     Because a `TestCase` can be run multiple times (in case of a retry),
     we use this field to group messages relating to the same attempt.
    """
    test_case_id: str
    timestamp: Timestamp
    worker_id: str | None = None
    """
    An identifier for the worker process running this test case, if test cases are being run in parallel. The identifier will be unique per worker, but no particular format is defined - it could be an index, uuid, machine name etc - and as such should be assumed that it's not human readable.
    """


@dataclass
class Exception(JSONDataclassMixin):
    type: str
    """
    The type of the exception that caused this result. E.g. "Error" or "org.opentest4j.AssertionFailedError"
    """
    message: str | None = None
    """
    The message of exception that caused this result. E.g. expected: "a" but was: "b"
    """
    stack_trace: str | None = None
    """
    The stringified stack trace of the exception that caused this result
    """


@dataclass
class TestRunStarted(JSONDataclassMixin):
    timestamp: Timestamp
    id: str | None = None


class Status(Enum):
    unknown = "UNKNOWN"
    passed = "PASSED"
    skipped = "SKIPPED"
    pending = "PENDING"
    undefined = "UNDEFINED"
    ambiguous = "AMBIGUOUS"
    failed = "FAILED"


@dataclass
class Duration(JSONDataclassMixin):
    seconds: int
    nanos: int
    """
    Non-negative fractions of a second at nanosecond resolution. Negative
     second values with fractions must still have non-negative nanos values
     that count forward in time. Must be from 0 to 999,999,999
     inclusive.
    """


@dataclass
class TestStepStarted(JSONDataclassMixin):
    test_case_started_id: str
    test_step_id: str
    timestamp: Timestamp


@dataclass
class TestRunHookStarted(JSONDataclassMixin):
    id: str
    """
    Unique identifier for this hook execution
    """
    test_run_started_id: str
    """
    Identifier for the test run that this hook execution belongs to
    """
    hook_id: str
    """
    Identifier for the hook that will be executed
    """
    timestamp: Timestamp


@dataclass
class UndefinedParameterType(JSONDataclassMixin):
    expression: str
    name: str


@dataclass
class Attachment(JSONDataclassMixin):
    body: str
    """
    *
     The body of the attachment. If `contentEncoding` is `IDENTITY`, the attachment
     is simply the string. If it's `BASE64`, the string should be Base64 decoded to
     obtain the attachment.
    """
    content_encoding: ContentEncoding
    """
    *
     Whether to interpret `body` "as-is" (IDENTITY) or if it needs to be Base64-decoded (BASE64).

     Content encoding is *not* determined by the media type, but rather by the type
     of the object being attached:

     - string: IDENTITY
     - byte array: BASE64
     - stream: BASE64
    """
    media_type: str
    """
    *
     The media type of the data. This can be any valid
     [IANA Media Type](https://www.iana.org/assignments/media-types/media-types.xhtml)
     as well as Cucumber-specific media types such as `text/x.cucumber.gherkin+plain`
     and `text/x.cucumber.stacktrace+plain`
    """
    file_name: str | None = None
    """
    *
     Suggested file name of the attachment. (Provided by the user as an argument to `attach`)
    """
    source: Source | None = None
    test_case_started_id: str | None = None
    test_step_id: str | None = None
    url: str | None = None
    """
    *
     A URL where the attachment can be retrieved. This field should not be set by Cucumber.
     It should be set by a program that reads a message stream and does the following for
     each Attachment message:

     - Writes the body (after base64 decoding if necessary) to a new file.
     - Sets `body` and `contentEncoding` to `null`
     - Writes out the new attachment message

     This will result in a smaller message stream, which can improve performance and
     reduce bandwidth of message consumers. It also makes it easier to process and download attachments
     separately from reports.
    """
    test_run_started_id: str | None = None


@dataclass
class DataTable(JSONDataclassMixin):
    location: Location
    rows: list[TableRow]


@dataclass
class Examples(JSONDataclassMixin):
    location: Location
    """
    The location of the `Examples` keyword
    """
    tags: list[Tag]
    keyword: str
    name: str
    description: str
    table_body: list[TableRow]
    id: str
    table_header: TableRow | None = None


@dataclass
class Step(JSONDataclassMixin):
    location: Location
    """
    The location of the steps' `keyword`
    """
    keyword: str
    """
    The actual keyword as it appeared in the source.
    """
    text: str
    id: str
    """
    Unique ID to be able to reference the Step from PickleStep
    """
    keyword_type: KeywordType | None = None
    """
    The test phase signalled by the keyword: Context definition (Given), Action performance (When), Outcome assertion (Then). Other keywords signal Continuation (And and But) from a prior keyword. Please note that all translations which a dialect maps to multiple keywords (`*` is in this category for all dialects), map to 'Unknown'.
    """
    doc_string: DocString | None = None
    data_table: DataTable | None = None


@dataclass
class SourceReference(JSONDataclassMixin):
    uri: str | None = None
    java_method: JavaMethod | None = None
    java_stack_trace_element: JavaStackTraceElement | None = None
    location: Location | None = None


@dataclass
class Ci(JSONDataclassMixin):
    name: str
    """
    Name of the CI product, e.g. "Jenkins", "CircleCI" etc.
    """
    url: str | None = None
    """
    Link to the build
    """
    build_number: str | None = None
    """
    The build number. Some CI servers use non-numeric build numbers, which is why this is a string
    """
    git: Git | None = None


@dataclass
class ParameterType(JSONDataclassMixin):
    name: str
    """
    The name is unique, so we don't need an id.
    """
    regular_expressions: list[str]
    prefer_for_regular_expression_match: bool
    use_for_snippets: bool
    id: str
    source_reference: SourceReference | None = None


@dataclass
class ParseError(JSONDataclassMixin):
    source: SourceReference
    message: str


@dataclass
class PickleTable(JSONDataclassMixin):
    rows: list[PickleTableRow]


@dataclass
class StepDefinition(JSONDataclassMixin):
    id: str
    pattern: StepDefinitionPattern
    source_reference: SourceReference


@dataclass
class TestCase(JSONDataclassMixin):
    id: str
    pickle_id: str
    """
    The ID of the `Pickle` this `TestCase` is derived from.
    """
    test_steps: list[TestStep]
    test_run_started_id: str | None = None
    """
    Identifier for the test run that this test case belongs to
    """


@dataclass
class TestCaseFinished(JSONDataclassMixin):
    test_case_started_id: str
    timestamp: Timestamp
    will_be_retried: bool


@dataclass
class TestRunFinished(JSONDataclassMixin):
    success: bool
    """
    A test run is successful if all steps are either passed or skipped, all before/after hooks passed and no other exceptions where thrown.
    """
    timestamp: Timestamp
    """
    Timestamp when the TestRun is finished
    """
    message: str | None = None
    """
    An informative message about the test run. Typically additional information about failure, but not necessarily.
    """
    exception: Exception | None = None
    """
    Any exception thrown during the test run, if any. Does not include exceptions thrown while executing steps.
    """
    test_run_started_id: str | None = None


@dataclass
class TestStepResult(JSONDataclassMixin):
    duration: Duration
    status: Status
    message: str | None = None
    """
    An arbitrary bit of information that explains this result. This can be a stack trace of anything else.
    """
    exception: Exception | None = None
    """
    Exception thrown while executing this step, if any.
    """


@dataclass
class TestRunHookFinished(JSONDataclassMixin):
    test_run_hook_started_id: str
    """
    Identifier for the hook execution that has finished
    """
    result: TestStepResult
    timestamp: Timestamp


@dataclass
class Background(JSONDataclassMixin):
    location: Location
    """
    The location of the `Background` keyword
    """
    keyword: str
    name: str
    description: str
    steps: list[Step]
    id: str


@dataclass
class Scenario(JSONDataclassMixin):
    location: Location
    """
    The location of the `Scenario` keyword
    """
    tags: list[Tag]
    keyword: str
    name: str
    description: str
    steps: list[Step]
    examples: list[Examples]
    id: str


@dataclass
class Hook(JSONDataclassMixin):
    id: str
    source_reference: SourceReference
    name: str | None = None
    tag_expression: str | None = None
    type: Type | None = None


@dataclass
class Meta(JSONDataclassMixin):
    protocol_version: str
    """
    *
     The [SEMVER](https://semver.org/) version number of the protocol
    """
    implementation: Product
    """
    SpecFlow, Cucumber-JVM, Cucumber.js, Cucumber-Ruby, Behat etc.
    """
    runtime: Product
    """
    Java, Ruby, Node.js etc
    """
    os: Product
    """
    Windows, Linux, MacOS etc
    """
    cpu: Product
    """
    386, arm, amd64 etc
    """
    ci: Ci | None = None


@dataclass
class PickleStepArgument(JSONDataclassMixin):
    doc_string: PickleDocString | None = None
    data_table: PickleTable | None = None


@dataclass
class TestStepFinished(JSONDataclassMixin):
    test_case_started_id: str
    test_step_id: str
    test_step_result: TestStepResult
    timestamp: Timestamp


@dataclass
class RuleChild(JSONDataclassMixin):
    background: Background | None = None
    scenario: Scenario | None = None


@dataclass
class PickleStep(JSONDataclassMixin):
    ast_node_ids: list[str]
    """
    References the IDs of the source of the step. For Gherkin, this can be
     the ID of a Step, and possibly also the ID of a TableRow
    """
    id: str
    """
    A unique ID for the PickleStep
    """
    text: str
    argument: PickleStepArgument | None = None
    type: Type1 | None = None
    """
    The context in which the step was specified: context (Given), action (When) or outcome (Then).

    Note that the keywords `But` and `And` inherit their meaning from prior steps and the `*` 'keyword' doesn't have specific meaning (hence Unknown)
    """


@dataclass
class Rule(JSONDataclassMixin):
    location: Location
    """
    The location of the `Rule` keyword
    """
    tags: list[Tag]
    """
    All the tags placed above the `Rule` keyword
    """
    keyword: str
    name: str
    description: str
    children: list[RuleChild]
    id: str


@dataclass
class Pickle(JSONDataclassMixin):
    id: str
    """
    *
     A unique id for the pickle
    """
    uri: str
    """
    The uri of the source file
    """
    name: str
    """
    The name of the pickle
    """
    language: str
    """
    The language of the pickle
    """
    steps: list[PickleStep]
    """
    One or more steps
    """
    tags: list[PickleTag]
    """
    *
     One or more tags. If this pickle is constructed from a Gherkin document,
     It includes inherited tags from the `Feature` as well.
    """
    ast_node_ids: list[str]
    """
    *
     Points to the AST node locations of the pickle. The last one represents the unique
     id of the pickle. A pickle constructed from `Examples` will have the first
     id originating from the `Scenario` AST node, and the second from the `TableRow` AST node.
    """


@dataclass
class FeatureChild(JSONDataclassMixin):
    rule: Rule | None = None
    background: Background | None = None
    scenario: Scenario | None = None


@dataclass
class Feature(JSONDataclassMixin):
    location: Location
    """
    The location of the `Feature` keyword
    """
    tags: list[Tag]
    """
    All the tags placed above the `Feature` keyword
    """
    language: str
    """
    The [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) language code of the Gherkin document
    """
    keyword: str
    """
    The text of the `Feature` keyword (in the language specified by `language`)
    """
    name: str
    """
    The name of the feature (the text following the `keyword`)
    """
    description: str
    """
    The line(s) underneath the line with the `keyword` that are used as description
    """
    children: list[FeatureChild]
    """
    Zero or more children
    """


@dataclass
class GherkinDocument(JSONDataclassMixin):
    comments: list[Comment]
    """
    All the comments in the Gherkin document
    """
    uri: str | None = None
    """
    *
     The [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)
     of the source, typically a file path relative to the root directory
    """
    feature: Feature | None = None


@dataclass
class Envelope(JSONDataclassMixin):
    attachment: Attachment | None = None
    gherkin_document: GherkinDocument | None = None
    hook: Hook | None = None
    meta: Meta | None = None
    parameter_type: ParameterType | None = None
    parse_error: ParseError | None = None
    pickle: Pickle | None = None
    source: Source | None = None
    step_definition: StepDefinition | None = None
    test_case: TestCase | None = None
    test_case_finished: TestCaseFinished | None = None
    test_case_started: TestCaseStarted | None = None
    test_run_finished: TestRunFinished | None = None
    test_run_started: TestRunStarted | None = None
    test_step_finished: TestStepFinished | None = None
    test_step_started: TestStepStarted | None = None
    test_run_hook_started: TestRunHookStarted | None = None
    test_run_hook_finished: TestRunHookFinished | None = None
    undefined_parameter_type: UndefinedParameterType | None = None
