<?php

declare(strict_types=1);

/**
 * This code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/codegen/codegen.rb]
 */

namespace Cucumber\Messages;

use JsonSerializable;
use Cucumber\Messages\DecodingException\SchemaViolationException;

/**
 * Represents the ExternalAttachment message in Cucumber's message protocol
 * @see https://github.com/cucumber/messages
 *
 * Represents an attachment that is stored externally rather than embedded in the message stream.
 *
 * This message type is used for large attachments (e.g., video files) that are already
 * on the filesystem and should not be loaded into memory. Instead of embedding the content,
 * only a URL reference is stored.
 *
 * A formatter or other consumer of messages may replace an Attachment with an ExternalAttachment if it makes sense to do so. */
final class ExternalAttachment implements JsonSerializable
{
    use JsonEncodingTrait;

    /**
     * Construct the ExternalAttachment with all properties
     *
     */
    public function __construct(

        /**
         * A URL where the attachment can be retrieved. This could be a file:// URL for
         * local filesystem paths, or an http(s):// URL for remote resources.
         */
        public readonly string $url = '',

        /**
         * The media type of the data. This can be any valid
         * [IANA Media Type](https://www.iana.org/assignments/media-types/media-types.xhtml)
         * as well as Cucumber-specific media types such as `text/x.cucumber.gherkin+plain`
         * and `text/x.cucumber.stacktrace+plain`
         */
        public readonly string $mediaType = '',

        /**
         * The identifier of the test case attempt if the attachment was created during the execution of a test step
         */
        public readonly ?string $testCaseStartedId = null,

        /**
         * The identifier of the test step if the attachment was created during the execution of a test step
         */
        public readonly ?string $testStepId = null,

        /**
         * The identifier of the test run hook execution if the attachment was created during the execution of a test run hook
         */
        public readonly ?string $testRunHookStartedId = null,

        /**
         * When the attachment was created
         */
        public readonly ?Timestamp $timestamp = null,
    ) {
    }

    /**
     * @throws SchemaViolationException
     *
     * @internal
     */
    public static function fromArray(array $arr): self
    {
        self::ensureUrl($arr);
        self::ensureMediaType($arr);
        self::ensureTestCaseStartedId($arr);
        self::ensureTestStepId($arr);
        self::ensureTestRunHookStartedId($arr);
        self::ensureTimestamp($arr);

        return new self(
            (string) $arr['url'],
            (string) $arr['mediaType'],
            isset($arr['testCaseStartedId']) ? (string) $arr['testCaseStartedId'] : null,
            isset($arr['testStepId']) ? (string) $arr['testStepId'] : null,
            isset($arr['testRunHookStartedId']) ? (string) $arr['testRunHookStartedId'] : null,
            isset($arr['timestamp']) ? Timestamp::fromArray($arr['timestamp']) : null,
        );
    }

    /**
     * @psalm-assert array{url: string|int|bool} $arr
     */
    private static function ensureUrl(array $arr): void
    {
        if (!array_key_exists('url', $arr)) {
            throw new SchemaViolationException('Property \'url\' is required but was not found');
        }
        if (array_key_exists('url', $arr) && is_array($arr['url'])) {
            throw new SchemaViolationException('Property \'url\' was array');
        }
    }

    /**
     * @psalm-assert array{mediaType: string|int|bool} $arr
     */
    private static function ensureMediaType(array $arr): void
    {
        if (!array_key_exists('mediaType', $arr)) {
            throw new SchemaViolationException('Property \'mediaType\' is required but was not found');
        }
        if (array_key_exists('mediaType', $arr) && is_array($arr['mediaType'])) {
            throw new SchemaViolationException('Property \'mediaType\' was array');
        }
    }

    /**
     * @psalm-assert array{testCaseStartedId?: string|int|bool} $arr
     */
    private static function ensureTestCaseStartedId(array $arr): void
    {
        if (array_key_exists('testCaseStartedId', $arr) && is_array($arr['testCaseStartedId'])) {
            throw new SchemaViolationException('Property \'testCaseStartedId\' was array');
        }
    }

    /**
     * @psalm-assert array{testStepId?: string|int|bool} $arr
     */
    private static function ensureTestStepId(array $arr): void
    {
        if (array_key_exists('testStepId', $arr) && is_array($arr['testStepId'])) {
            throw new SchemaViolationException('Property \'testStepId\' was array');
        }
    }

    /**
     * @psalm-assert array{testRunHookStartedId?: string|int|bool} $arr
     */
    private static function ensureTestRunHookStartedId(array $arr): void
    {
        if (array_key_exists('testRunHookStartedId', $arr) && is_array($arr['testRunHookStartedId'])) {
            throw new SchemaViolationException('Property \'testRunHookStartedId\' was array');
        }
    }

    /**
     * @psalm-assert array{timestamp?: array} $arr
     */
    private static function ensureTimestamp(array $arr): void
    {
        if (array_key_exists('timestamp', $arr) && !is_array($arr['timestamp'])) {
            throw new SchemaViolationException('Property \'timestamp\' was not array');
        }
    }
}
