<?php

declare(strict_types=1);

/**
 * This code was auto-generated by {this script}[https://github.com/cucumber/messages/blob/main/codegen/codegen.rb]
 */

namespace Cucumber\Messages\StepDefinitionPattern;

enum Type: string
{
    case CUCUMBER_EXPRESSION = 'CUCUMBER_EXPRESSION';
    case REGULAR_EXPRESSION = 'REGULAR_EXPRESSION';
}
