name: Release Python

on:
  push:
    branches: [release/*]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: python
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: cucumber/action-publish-pypi@v3.0.0
        with:
          working-directory: "python"
