name: test-ruby

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - ruby/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - ruby/**
      - Makefile
      - .github/**

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@6e5d382445ae5590b7449d8b3bc8cb1c2c27f617 # v1.317.0
        with:
          ruby-version: '4.0.5'
          bundler-cache: true
          working-directory: ruby
      - run: bundle exec rubocop
        working-directory: ruby

  test-ruby:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby: ['3.3', '3.4', '4.0']
        include:
          - os: macos-latest
            ruby: '4.0'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@6e5d382445ae5590b7449d8b3bc8cb1c2c27f617 # v1.317.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ruby
      - run: bundle exec rake
        working-directory: ruby
