name: test-perl

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - perl/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - perl/**
      - Makefile
      - .github/**

jobs:
  test-perl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@0f3cc9bc0b055cc20750d218061ebbdebd101bb3 # v2.1
        with:
          cpanfile: "perl/cpanfile"

      - name: run tests
        run: |
          prove -l
          AUTHOR_TESTS=1 prove -l
        working-directory: perl
