name: Code Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  codegen:
    name: Generate code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Generate code from schema
        uses: docker/bake-action@v2
        with:
          targets: codegen

      - name: Check the repo is still clean after generation
        run: |
          git status --porcelain
          git diff HEAD
          [ -z "$(git status --porcelain)" ]
