name: test-perl

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - perl/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - perl/**
      - Makefile
      - .github/**

jobs:
  test-perl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@8ec40bce95c287169e8c13551e5e49d0185ce955 # v2.2
        with:
          cpanfile: "perl/cpanfile"

      - name: run tests
        run: |
          prove -l
          AUTHOR_TESTS=1 prove -l
        working-directory: perl
