name: test-cpp

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - cpp/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - cpp/**
      - Makefile
      - .github/**

jobs:
  test-cpp:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            cc: gcc
          - os: ubuntu-latest
            cc: clang
          - os: macos-latest
            cc: clang
          - os: windows-latest
            cc: cl
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build
      - name: Configure
        working-directory: cpp
        run: |
          cmake -S . -B ./build -G=Ninja -DCPM_SOURCE_CACHE=$HOME/.cache/CPM
      - name: Build
        working-directory: cpp
        run: |
          cmake --build ./build
      - name: Install
        working-directory: cpp
        run: |
          sudo cmake --install ./build
