name: test-elixir

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - elixir/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - elixir/**
      - Makefile
      - .github/**

jobs:
  test-elixir:
    name: Test Elixir
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Beam
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: '27.3'
          elixir-version: '1.17'

      - run: mix deps.get
        working-directory: elixir
      - run: mix test
        working-directory: elixir
