name: test-codegen

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - jsonschema/**
      - codegen/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - Makefile
      - .github/**
      - jsonschema/**
      - codegen/**
      - cpp/**
      - dart/**
      - dotnet/**
      - elixir/**
      - go/**
      - java/**
      - javascript/**
      - perl/**
      - php/**
      - python/**
      - ruby/**

jobs:
  test-codegen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.x
          cache: "npm"
          cache-dependency-path: jsonschema/package-lock.json

      - name: Set up Ruby
        uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: '4.0.5'

      - name: generate code for all languages
        run: |
          make clean
          make generate

      - name: check the repo is still clean after generation
        run: |
          git status --porcelain
          git diff HEAD
          [ -z "$(git status --porcelain)" ]
