name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  codegen:
    name: Generate code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Generate code from schema
        uses: docker/bake-action@v2
        with:
          targets: codegen
          set: |
            java-codegen.cache-to=type=gha,scope=java-codegen,mode=max
            java-codegen.cache-from=type=gha,scope=java-codegen
            javascript-codegen.cache-to=type=gha,scope=javascript-codegen,mode=max
            javascript-codegen.cache-from=type=gha,scope=javascript-codegen
            php-codegen.cache-to=type=gha,scope=php-codegen,mode=max
            php-codegen.cache-from=type=gha,scope=php-codegen
            ruby-codegen.cache-to=type=gha,scope=ruby-codegen,mode=max
            ruby-codegen.cache-from=type=gha,scope=ruby-codegen

      - name: Check the repo is still clean after generation
        run: |
          git status --porcelain
          git diff HEAD
          [ -z "$(git status --porcelain)" ]

  test-java:
    needs: codegen
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '16']

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Test
        uses: docker/bake-action@v2
        with:
          targets: java-test
          set: |
            *.contexts.schema-codegen=
            java-test.args.JAVA_VERSION=${{ matrix.java }}
            java-test.cache-to=type=gha,scope=java-test-${{ matrix.java }},mode=max
            java-test.cache-from=type=gha,scope=java-test-${{ matrix.java }}

  test-java-mac-windows:
    needs: test-java
    name: Java ${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            java: "16"
          - os: macos-latest
            java: "16"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"

      - run: mvn install
        working-directory: java

      - run: mvn test
        working-directory: java

      - run: ./scripts/check-jar.sh
        working-directory: java

  test-javascript:
    needs: codegen
    name: Javascript ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16', '17', '18']

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Test
        uses: docker/bake-action@v2
        with:
          targets: javascript-test
          set: |
            *.contexts.schema-codegen=
            javascript-test.args.NODE_VERSION=${{ matrix.node }}
            javascript-test.cache-to=type=gha,scope=javascript-test-${{ matrix.node }},mode=max
            javascript-test.cache-from=type=gha,scope=javascript-test-${{ matrix.node }}

  test-javascript-mac-windows:
    name: Javascript 18 ${{ matrix.os }}
    needs: test-javascript
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            node-version: "18.x"
          - os: macos-latest
            node-version: "18.x"

    steps:
      - name: set git core.autocrlf to 'input'
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v3

      - name: with Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: javascript/package-lock.json

      - run: npm install-ci-test
        working-directory: javascript

  test-php:
    needs: codegen
    name: PHP ${{ matrix.php }} ${{ matrix.composer-extra-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '8.1'
            composer-extra-flags: '--prefer-lowest'
          - php: '8.1'
            composer-extra-flags: ''

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Test
        uses: docker/bake-action@v2
        with:
          targets: php-test
          set: |
            *.contexts.schema-codegen=
            php-test.args.PHP_VERSION=${{ matrix.php }}
            php-test.args.COMPOSER_EXTRA_FLAGS=${{ matrix.composer-extra-flags }}
            php-test.cache-to=type=gha,scope=php-test-${{ matrix.php }}${{ matrix.composer-extra-flags }},mode=max
            php-test.cache-from=type=gha,scope=php-test-${{ matrix.php }}${{ matrix.composer-extra-flags }}

  test-ruby:
    needs: codegen
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1']

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Test
        uses: docker/bake-action@v2
        with:
          targets: ruby-test
          set: |
            *.contexts.schema-codegen=
            ruby-test.args.RUBY_VERSION=${{ matrix.ruby }}
            ruby-test.cache-to=type=gha,scope=ruby-test-${{ matrix.ruby }},mode=max
            ruby-test.cache-from=type=gha,scope=ruby-test-${{ matrix.ruby }}

  test-ruby-mac:
    needs: test-ruby
    name: Ruby ${{ matrix.ruby }} MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        ruby: ['3.1']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ruby

      - run: bundle exec rake
        working-directory: ruby
