name: test-elixir

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - elixir/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - elixir/**
      - Makefile
      - .github/**

jobs:
  test-elixir:
    name: Test Elixir
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Beam
        uses: erlef/setup-beam@ee09b1e59bb240681c382eb1f0abc6a04af72764 # v1.23.0
        with:
          otp-version: '27.1'
          elixir-version: '1.17'

      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0

      - name: Run Tests
        run: make
        working-directory: elixir

