name: test-elixir

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - elixir/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - elixir/**
      - Makefile
      - .github/**

jobs:
  test-elixir:
    name: Test Elixir
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Setup Beam
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: '27.1'
          elixir-version: '1.17'

      - run: |
          mix local.hex --force
          mix deps.get
        working-directory: elixir

      - run: mix test
        working-directory: elixir
