name: test-python

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - .pre-commit-config.yaml
      - python/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - python/**
      - Makefile
      - .github/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: 'windows-latest', python-version: '3.13', toxenv: 'py' }
          - { os: 'macos-latest', python-version: '3.13', toxenv: 'py' }
          # Running linting through latest Python
          - { os: 'ubuntu-latest', python-version: '3.13', toxenv: 'lint,py' }
        os: ['ubuntu-latest']
        python-version: ['3.9', '3.10', '3.11', '3.12', 'pypy3.10', 'pypy3.11']
        toxenv: ['py']
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "0.11.2"

      - name: Linting and testing
        run: |
          uv tool install tox --with tox-uv
          tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: python/coverage.xml

      - name: Build package
        run: uv build
