name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  codegen:
    name: Generate code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Generate code from schema
        uses: docker/bake-action@v2
        with:
          targets: codegen

      - name: Check the repo is still clean after generation
        run: |
          git status --porcelain
          git diff HEAD
          [ -z "$(git status --porcelain)" ]

  test-javascript:
    needs: codegen
    name: Javascript ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16', '17', '18']

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Test
        uses: docker/bake-action@v2
        with:
          targets: javascript-test
          set: |
            javascript-test.args.NODE_VERSION=${{ matrix.node }}

  test-javascript-mac-windows:
    name: Javascript 18 ${{ matrix.os }}
    needs: test-javascript
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            node-version: "18.x"
          - os: macos-latest
            node-version: "18.x"

    steps:
      - name: set git core.autocrlf to 'input'
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v3

      - name: with Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: javascript/package-lock.json

      - run: npm install-ci-test
        working-directory: javascript

  test-php:
    needs: codegen
    name: PHP ${{ matrix.php }} ${{ matrix.composer-extra-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '8.1'
            composer-extra-flags: '--prefer-lowest'
          - php: '8.1'
            composer-extra-flags: ''

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Test
        uses: docker/bake-action@v2
        with:
          targets: php-test
          set: |
            php-test.args.PHP_VERSION=${{ matrix.php }}
            php-test.args.COMPOSER_EXTRA_FLAGS=${{ matrix.composer-extra-flags }}

  test-ruby:
    needs: codegen
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1']

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Test
        uses: docker/bake-action@v2
        with:
          targets: ruby-test
          set: |
            ruby-test.args.RUBY_VERSION=${{ matrix.ruby }}

  test-ruby-mac:
    needs: test-ruby
    name: Ruby 3.1 MacOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
          working-directory: ruby

      - run: bundle exec rake
        working-directory: ruby
