name: test-codegen

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - jsonschema/**
      - codegen/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - Makefile
      - .github/**
      - jsonschema/**
      - codegen/**
      - cpp/**
      - dotnet/**
      - elixir/**
      - go/**
      - java/**
      - javascript/**
      - perl/**
      - php/**
      - python/**
      - ruby/**

jobs:
  test-codegen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: jsonschema/package-lock.json

      - name: Set up Ruby
        uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735 # v1.305.0
        with:
          ruby-version: '3.4.9'

      - name: generate code for all languages
        run: |
          make clean
          make generate

      - name: check the repo is still clean after generation
        run: |
          git status --porcelain
          git diff HEAD
          [ -z "$(git status --porcelain)" ]
